Документ №1183092735 от 2021-09-13 Колпаков М.А.
saby/android-sabycom pull request #1
Opened 2021-09-13 15:06 UTC by github-auto-merge

https://online.sbis.ru/doc/920e5bb9-a323-4414-92dd-3cca1e4f20a1  Разработать демо приложение для Sabycom и базовую версию виджета

2021-09-15 11:36 UTC, sv-bubenschikov commented on sabycom/build.gradle
> +        minSdkVersion 24
@MAKolpakov почему именно 24 версия (не 21)

2021-09-15 12:11 UTC, MAKolpakov commented on sabycom/build.gradle
> +        minSdkVersion 24
Обсудим

2021-09-15 12:12 UTC, MAKolpakov commented
@sv-bubenschikov сделаем 21

2021-09-15 12:13 UTC, MAKolpakov commented on sabycom/build.gradle
> +        minSdkVersion 24
sv-bubenschikov сделаем 21

2021-09-15 13:21 UTC, sv-bubenschikov requested changes

2021-09-15 13:21 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tenzor/sabycom/widget/SabycomDialog.kt
> +    @SuppressLint("SetJavaScriptEnabled")
Нужен комментарий, почему так можно

2021-09-15 13:21 UTC, sv-bubenschikov commented on sabycom/src/main/res/layout/sabycom_dialog.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Нужен ли внешний контейнер?

2021-09-15 13:21 UTC, sv-bubenschikov commented on sabycom/src/main/res/values/colors.xml
> +<resources>
Удалить лишние ресурсы

2021-09-15 13:21 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tenzor/sabycomdemo/SabycomDemoActivity.kt
> +        Sabycom.registerUser(UserData(UUID.fromString(stringUUID)))
Нужно приблизится к MVVM. перенести взаимодействие с сервисами во вьюмодель. Можно AndroidViewModel

2021-09-15 13:21 UTC, sv-bubenschikov commented on sabycomdemo/src/main/res/layout/activity_sabycom_demo.xml
> +        android:layout_marginBottom="-15dp"
Можно оформить только ограничениями

2021-09-15 13:21 UTC, sv-bubenschikov commented on sabycom/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET" />
Каждое разрешение должно быть подписано "Для чего"

2021-09-15 13:21 UTC, sv-bubenschikov commented on sabycomdemo/build.gradle
> +    implementation project(path: ':sabycom')
Рекомендую внутренние зависимости. размещать в начале блока dependencies

2021-09-16 15:05 UTC, sv-bubenschikov requested changes
Доработано не всё

2021-09-16 15:05 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tenzor/sabycomdemo/SabycomDemoActivity.kt
> +        Sabycom.registerUser(UserData(UUID.fromString(stringUUID)))
✅

2021-09-16 15:06 UTC, sv-bubenschikov reviewed
В следующей итерации нужно будет расставить меток `@WorkerThread`, `@MainThread`

2021-09-17 11:25 UTC, sv-bubenschikov commented on sabycom/build.gradle
> +        versionName "1.0"
Обсудили, пока нет версионирования ✅

2021-09-17 11:25 UTC, sv-bubenschikov commented on sabycomdemo/src/main/AndroidManifest.xml
> +    package="ru.tenzor.sabycomdemo">
✅

2021-09-17 11:25 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tenzor/sabycom/widget/SabycomDialog.kt
> +    private fun getOrCreateArguments(): Bundle {
✅

2021-09-17 11:26 UTC, sv-bubenschikov approved these changes

2021-09-17 12:45 UTC, merged