Документ №1183585023 от 2021-10-29 Колпаков М.А.
saby/android-sabycom pull request #10
Opened 2021-11-30 09:00 UTC by github-auto-merge

https://online.sbis.ru/doc/72caf886-4893-48fe-b8f5-e01c707a3687  Доработать Демо приложение мобильный консультант,<br>Сделать кастомизацию пользовательских данных, переключение стендов, привести UI в соответствие с iOs.

2021-11-30 19:50 UTC, sv-bubenschikov requested changes

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/DemoUtils.kt
> +        //ignore
Тяжеловать без логирования. Уже есть задача, чтобы подключить?

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/demo/DemoViewModel.kt
> +
Достаточно ViewModel, не используются особенности AndroidViewModel. Лишняя строка

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/demo/DemoViewModel.kt
> +        Sabycom.unreadConversationCount(object : UnreadCounterCallback {
Ссылка самостоятельно потеряется? Не нужно занулять?

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/Event.kt
> +internal open class Event<out T>(private val content: T) {
open не используется

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/Event.kt
> +    fun getContentIfNotHandled(): T? {
Предлагаю более удобную в использвовании реализацию
```kotlin
fun handleEvent(handler: (T) -> Unit) {
    if (!isHandled) {
        isHandled = true
        handler(content)
    }
}
```

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsFragment.kt
> +                viewModel.stand = position
Предлагаю переименовать везде, где используется stand. Слово имеет другое значение - стоять. Можно remote, host или что-то в этом духе

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsFragment.kt
> +            addToBackStack("Demo")
Для чего это? Переходов по экранам вроде нет в приложении

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsViewModel.kt
> +            errorMessageLiveData.value = "Поле appId обзязательно"
Application на руках, можно вынести в ресурсы

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsViewModel.kt
> +        stand = getStandId(sharedPreferences.getString(CURRENT_STAND_KEY, null) ?: "prod")
Обязательно должно быть. Дублировать термин "prod" не нужно

2021-11-30 19:50 UTC, sv-bubenschikov commented on sabycomdemo/src/main/res/values/strings.xml
> +    <string name="restart_app">Переинициализировать</string>
Сложное слово. Перезапустить не подойдёт?

2021-12-01 07:02 UTC, MAKolpakov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/DemoUtils.kt
> +        //ignore
@sv-bubenschikov  нет пока обходимся стандартными средствами. Добавил логирование.

2021-12-01 07:09 UTC, MAKolpakov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/demo/DemoViewModel.kt
> +        Sabycom.unreadConversationCount(object : UnreadCounterCallback {
@sv-bubenschikov  она живет все время работы приложения и  умрет вместе с синглетном.

2021-12-01 07:15 UTC, MAKolpakov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsFragment.kt
> +            addToBackStack("Demo")
@sv-bubenschikov  Для того чтобы вернуться на экран настроек по нажатию кнопки назад

2021-12-01 07:22 UTC, MAKolpakov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsViewModel.kt
> +        stand = getStandId(sharedPreferences.getString(CURRENT_STAND_KEY, null) ?: "prod")
@sv-bubenschikov  при первом запуске  в sharedPreferences еще пусто,  для этого надо значение по умолчанию

2021-12-01 18:16 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/demo/DemoViewModel.kt
> +        Sabycom.unreadConversationCount(object : UnreadCounterCallback {
Получается, DemoViewModel утекает - плохой пример. Нужно, чтобы пользователи обратили внимание на это и затирали ссылку

2021-12-01 18:17 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsFragment.kt
> +                viewModel.stand = position
Не критично сейчас

2021-12-01 18:24 UTC, sv-bubenschikov commented on sabycomdemo/src/main/java/ru/tensor/sabycomdemo/settings/SettingsViewModel.kt
> +        stand = getStandId(sharedPreferences.getString(CURRENT_STAND_KEY, null) ?: "prod")
Сейчас из-за дублирования ошибка: ищется "prod", а в R.array.hosts есть только "PROD". Поиск indexOf() регистрозависимый

2021-12-07 05:22 UTC, closed without merging