Документ №1184084359 от 2021-12-09 Старцева Г.В.
saby/android-sabycom pull request #42
Opened 2021-12-18 13:53 UTC by github-auto-merge

https://online.sbis.ru/doc/b3c3c3ef-d21c-42fc-a1ea-198a16c4299b  Web-виджеты Android. Нельзя добавить вложение в чат на стороне клиента, странного происходит скачивание вложений, которые отправил оператор<br>скачать sabycom <br>открыть приложение - id 4553e85c-344d-48bf-86b9-4db74f44fca8 - фикс стенд - Анонимный пользователь<br>Написать в чат - Попытаться добавить вложение <br>Под оператором админтп/Пароль123 - К-центр - Взять в работу - Отправить вложение<br>Таб по вложению<br>ФР: <br>нельзя загрузить вложение (ничего не происходит)<br>при скачивается на мгновение экран становится белым не понятно что произошло<br>ОР: <br>можно загрузить вложение <br>появляется окошко с вопросом скачать/отменить, либо происходит сразу скачивание, но понятно что оно прошло, можно сразу открыть скаченный файл<br>consultant 21.6213-5 от 08.12.2021<br>android sabycom 21.6219-19<br>Android 11/планшет

2021-12-20 04:54 UTC, sv-bubenschikov requested changes

2021-12-20 04:54 UTC, sv-bubenschikov commented on sabycom/src/main/AndroidManifest.xml
> +    <!--Разрешение для скачивания отправки файлов из виджета "мобильный консультант" -->
`скачивания отправки` - не понял комментария

2021-12-20 04:54 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/SabycomDialog.kt
> +        binding.webView.onDestroy()
Тут уже нет view. Нужно вызывать в `onDestroyView()`

2021-12-20 04:54 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/SabycomDialog.kt
>      private lateinit var binding: SabycomDialogBinding
Утекает контекст. Нужно занулять ссылку в `onDestroyView()`

2021-12-20 04:54 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/SabycomDialog.kt
> +internal class SabycomDialog : BottomSheetDialogFragment(), AdvancedWebView.Listener {
Предлагаю оформить реалиазацию AdvancedWebView самостоятельным классом. Много лишнего появляется в SabycomDialog

2021-12-20 07:41 UTC, MAKolpakov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/SabycomDialog.kt
>      private lateinit var binding: SabycomDialogBinding
@sv-bubenschikov  избавился от хранения биндинга.

2021-12-21 04:40 UTC, sv-bubenschikov requested changes

2021-12-21 04:40 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/SabycomDialog.kt
> +    private lateinit var webView: AdvancedWebView
@MAKolpakov утекает, нужно занулять ссылку на view. Не хранить дольше onDestroyView()

2021-12-21 04:40 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/webview/WebViewFileLoader.kt
> +internal class WebViewFileLoader(private val contextProvider: () -> Context?) : AdvancedWebView.Listener,
@MAKolpakov используется как not null context

2021-12-21 04:40 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/webview/WebViewFileLoader.kt
> +        contextProvider.invoke()?.let { context ->
@MAKolpakov можно заменить на contextProvider()

2021-12-21 04:40 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/webview/WebViewFileLoader.kt
> +    var permissionLauncher: ActivityResultLauncher<String>?=null
@MAKolpakov обязательно будет - lateinit

2021-12-21 04:40 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/SabycomDialog.kt
> +        webViewFileLoader.permissionLauncher =
@MAKolpakov в webViewFileLoader можно передать не только провайдер контекста, а сам фрагмент. Тогда все инициализации можно будет внутри скрыть. Не будет цикличных присвоений на стороне фрагмента

2021-12-21 04:40 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/webview/WebViewFileLoader.kt
> +        suggestedFilename: String?,
@MAKolpakov никогда не null. Проверь по остальным аргументам
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/90767231/146871961-2d0c0dd2-71d9-451f-a09a-eff3194bed84.png">

2021-12-21 04:40 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/webview/WebViewFileLoader.kt
> +    private var fileName: String? = null
@MAKolpakov fileUrl и fileName никогда не присваиваются

2021-12-21 12:24 UTC, merged