Документ №1183101449 от 2021-09-14 Колпаков М.А.
saby/android-sabycom pull request #5
Opened 2021-11-01 06:54 UTC by github-auto-merge

https://online.sbis.ru/doc/3966a770-62ae-4965-a6aa-732aea72b57c  Реализовать запрос количества непрочитанных сообщений.<br>unreadConversationCount()

2021-11-08 10:03 UTC, sv-bubenschikov requested changes

2021-11-08 10:03 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/Sabycom.kt
>       * Запросить количество непрочитанных сообщений асинхронно.
Не соответствует действительности. Метод не запускает запрос, а только устнавливает обработчик. Результаты доставляются в главном потоке

2021-11-08 10:11 UTC, MAKolpakov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/repository/SabycomLocalRepository.kt
> +        val userId = sharedPreferences.getString(USER_DATA_ID_KEY, null) ?: throw IllegalStateException(NOT_INIT_ERROR)
@sv-bubenschikov в данном случае нет, если нет данных значит не провели инициализацию, и тогда работать ни чего не будет. Нужно об это сообщить как можно громче =)

2021-11-08 10:18 UTC, MAKolpakov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/js/JSInterface.kt
> +        println(data)
@sv-bubenschikov  удалю, здесь этого вообще не надо.

2021-11-08 10:23 UTC, MAKolpakov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/repository/SabycomRemoteRepository.kt
> +
@sv-bubenschikov думаю нет смысла что то подключать, наверное воспользуюсь cтандартным Log.d()

2021-11-08 18:33 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/repository/SabycomLocalRepository.kt
> +        val userId = sharedPreferences.getString(USER_DATA_ID_KEY, null) ?: throw IllegalStateException(NOT_INIT_ERROR)
@MAKolpakov  с исключением согласен, но это не ответственность кэша. Нужно в это проделать на уровне репозитория, а то и выше

2021-11-08 18:34 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/repository/SabycomRemoteRepository.kt
> +
@MAKolpakov вариант. Или можно определить интерфейс LogConsumer, чтобы прикладной код мог свой блоггер подсунуть

2021-11-09 10:51 UTC, MAKolpakov commented on sabycom/src/main/java/ru/tensor/sabycom/widget/repository/SabycomRemoteRepository.kt
> +
@sv-bubenschikov думаю пока это "овер-инжиниринг", возможно потом что то такое добавим

2021-11-09 14:24 UTC, sv-bubenschikov commented on sabycom/src/main/java/ru/tensor/sabycom/Sabycom.kt
> +     * Зарегестрировать обработчик изсенения количества непрочитанных соощений.
@MAKolpakov тут какое-то странное слово `изсенения`, поправь потом

2021-11-09 14:54 UTC, merged